package presentacion;

import view.viewPrestamo;
import view.viewInicio;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
import javax.swing.Timer;               
import utilidades.BtnChangeColor;
import view.viewDevolucion;
import view.viewLibro;
import view.viewUsuario;
/**
 *
 * @author dubig
 */
public class Dashboard extends javax.swing.JFrame {
    private javax.swing.Timer reloj;
 
    
    public Dashboard() {
        initComponents();
        SetDate();
        iniciarActualizacionHora();
        InitContent();
       
    }
    
   
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menú = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jgrid = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnDevoluciones = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fechatexto = new javax.swing.JLabel();
        horalocal = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Menú.setBackground(new java.awt.Color(255, 102, 102));
        Menú.setPreferredSize(new java.awt.Dimension(270, 640));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Book");

        Jgrid.setBackground(new java.awt.Color(255, 102, 102));
        Jgrid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jgrid.setOpaque(false);
        Jgrid.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        btnInicio.setText("Inicio");
        btnInicio.setAutoscrolls(true);
        btnInicio.setBorder(null);
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        Jgrid.add(btnInicio);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        Jgrid.add(btnUsuarios);

        btnLibros.setText("Libros");
        btnLibros.setFocusPainted(false);
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        Jgrid.add(btnLibros);

        btnPrestamos.setText("Prestamos");
        btnPrestamos.setFocusPainted(false);
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        Jgrid.add(btnPrestamos);

        btnDevoluciones.setText("Devoluciones");
        btnDevoluciones.setFocusPainted(false);
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });
        Jgrid.add(btnDevoluciones);

        javax.swing.GroupLayout MenúLayout = new javax.swing.GroupLayout(Menú);
        Menú.setLayout(MenúLayout);
        MenúLayout.setHorizontalGroup(
            MenúLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenúLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(MenúLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jgrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenúLayout.setVerticalGroup(
            MenúLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenúLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(Jgrid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(255, 0, 51));
        Header.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administración/Control/Biblioteca");

        fechatexto.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        fechatexto.setForeground(new java.awt.Color(255, 255, 255));
        fechatexto.setText("Hoy es {dayname}  {day} de {month} de {year}");

        horalocal.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        horalocal.setForeground(new java.awt.Color(255, 255, 255));
        horalocal.setText("Hora local Perú: ");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fechatexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HeaderLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(horalocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108)))
                .addGap(18, 18, 18))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(horalocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(fechatexto)
                .addGap(15, 15, 15))
        );

        Contenido.setBackground(new java.awt.Color(204, 204, 204));
        Contenido.setPreferredSize(new java.awt.Dimension(750, 430));
        Contenido.setLayout(new java.awt.BorderLayout());

        Mensaje.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        Mensaje.setText("!Bienvenido!");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Menú, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Menú, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Header.setVisible(true);
        ShowJPanel(new viewInicio());
        BtnChangeColor.actualizarColoresBotones(btnInicio,
                btnInicio, btnUsuarios, btnLibros, btnPrestamos, btnDevoluciones
        );
        
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        Header.setVisible(false);
        ShowJPanel(new viewUsuario());
        BtnChangeColor.actualizarColoresBotones(btnUsuarios,
                btnUsuarios, btnInicio, btnLibros, btnPrestamos, btnDevoluciones
        );
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        Header.setVisible(false);
        ShowJPanel(new viewLibro());
        BtnChangeColor.actualizarColoresBotones(btnLibros,
                btnLibros, btnUsuarios, btnInicio, btnPrestamos, btnDevoluciones
        );
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        Header.setVisible(true);
        ShowJPanel(new viewPrestamo());
         BtnChangeColor.actualizarColoresBotones(btnPrestamos,
                btnPrestamos, btnUsuarios, btnLibros, btnInicio, btnDevoluciones
        );
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        Header.setVisible(false);
        ShowJPanel(new viewDevolucion());
        BtnChangeColor.actualizarColoresBotones(btnDevoluciones,
                btnDevoluciones, btnUsuarios, btnLibros, btnPrestamos, btnInicio
        );
    }//GEN-LAST:event_btnDevolucionesActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Jgrid;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPanel Menú;
    private javax.swing.JButton btnDevoluciones;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel fechatexto;
    private javax.swing.JLabel horalocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

 public void SetDate() {
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String [] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "; Septiembre","Octubre", "Noviembre"
            , "Diciembre"};
    fechatexto.setText("Hoy es "+dia+" de "+meses[month-1]+" de "+year);
}
 
  private void InitContent(){
    }
  
  private void ShowJPanel(JPanel Jpanel){
      Jpanel.setSize(750,430);
      Jpanel.setLocation(0,0);
      
      Contenido.removeAll();
      Contenido.add(Jpanel, BorderLayout.CENTER);
      Contenido.revalidate();
      Contenido.repaint();
  
  
  }
  
  
  
  
 private void actualizarhoraperu(){
      ZonedDateTime horaPeru = ZonedDateTime.now(ZoneId.of("America/Lima"));
        horalocal.setText("Hora local Perú: " +
            horaPeru.format(DateTimeFormatter.ofPattern("HH:mm:ss")));
 }
 private void iniciarActualizacionHora() {
    
     reloj = new Timer(1_000, e -> actualizarhoraperu());
     reloj.start();
     
    }
 
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    
    

    
}
    
 

